DROP TABLE IF EXISTS `CAR_CATEGORY`;
CREATE TABLE `CAR_CATEGORY` (
  `CATEGORY_NAME` varchar(25) NOT NULL,
  `NO_OF_LUGGAGE` int(11) NOT NULL,
  `NO_OF_PERSON` int(11) NOT NULL,
  `COST_PER_DAY` int(11) NOT NULL,
  `LATE_FEE_PER_HOUR` int(11) NOT NULL,
  PRIMARY KEY (`CATEGORY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
